import Context from "./_context/appContext";
import NavBar from "./_ui/navBar";
import "./globals.css";

export const metadata = {
  title: "SlumberSphere",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className=""
      >
       <Context>
         <NavBar/>
        {children}
       </Context>
      </body>
    </html>
  );
}
